### ISSUE TITLE
Reproduced with a little change

### ISSUE THREAD

**Issue by DreamInvoker** [wkcn/LookaheadOptimizer-mx#1]
Thank you for providing such simple reproduction.
I reproduced it by make the following change in line 37 (ps: I use the module version of MXNET):
from 
`update_func(indexes, weights, grads, states)`
to
`update_func(indexes[0], weights[0], grads[0], states)`

otherwise, i will get the error :

Traceback (most recent call last):
  File "/projects/LookaheadOptimizer-mx/mnist.py", line 148, in <module>
    train(opt.epochs, ctx)
  File "/projects/LookaheadOptimizer-mx/mnist.py", line 124, in train
    trainer.step(data.shape[0])
  File "/projects/LookaheadOptimizer-mx/mxnet/gluon/trainer.py", line 199, in step
    upd(i, grad, arr)
  File "/projects/LookaheadOptimizer-mx/mxnet/optimizer.py", line 1282, in __call__
    self.optimizer.update_multi_precision(index, weight, grad, self.states[index])
  File "/projects/LookaheadOptimizer-mx/lookahead_optimizer.py", line 27, in update_multi_precision
    index, weight, grad, state, self._parent_cls.update_multi_precision)
  File "/projects/LookaheadOptimizer-mx/lookahead_optimizer.py", line 38, in _lookahead_update_impl
    update_func(indexes, weights, grads, states)
  File "/projects/LookaheadOptimizer-mx/mxnet/optimizer.py", line 536, in update_multi_precision
    multi_precision=use_multi_precision)
  File "/projects/LookaheadOptimizer-mx/mxnet/optimizer.py", line 503, in _update_impl
    assert(isinstance(weight, NDArray))
AssertionError

Thank you if you know what happened, please feel free to comment below.

**Comment by wkcn** [comment]
Sorry that I reply late. I will commit a reproduction based on MXNet module.

**Comment by DreamInvoker** [comment]
Thanks very much.

**Comment by wkcn** [comment]
@DreamInvoker Hi, have you addressed the problem?
I run the optimizer on [`https://github.com/apache/incubator-mxnet/tree/master/example/image-classification/train_mnist.py`](https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/train_mnist.py). It works.

**Comment by DreamInvoker** [comment]
Yes, I simply changed the code as the first comment described above. Thank you for your reply and other reproduction for MXnet module version. 😃😃😃
